spring:
  application:
    name: "gateway"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret: "secret"
  accessTokenMaxAgeInMinutes: 5
  refreshTokenMaxAgeInMinutes: 4320

swagger:
  config:
    refreshRate: 30000
