version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  backend:
    docker:
      - image: cimg/openjdk:17.0.1
    
    working_directory: ~/repo/backend
    
    steps:
      - checkout:
        path: ~/repo
      - run:
          name: Build
          command: |
            cd ./backend/
            mvn -B -DskipTests clean package
      - run:
          name: Test
          command: |
            cd ./backend/
            mvn test
    
  frontend:
    docker:
      - image: cimg/node:18.0.0
    
    working_directory: ~/repo/frontend
    
    steps:
      - checkout:
         path: ~/repo
      - node/install-packages:
         pkg-manager: npm
      - run:
         name: Test
         command: npm test
      - run:
         name: Build
         command: npm build

# Invoke jobs via workflows
workflows:
  sample:
    jobs:
      - backend
      - frontend
