version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  backend:
    docker:
      - image: cimg/openjdk:17.0.1

    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd ./backend/
            mvn -B -DskipTests clean package
      - run:
          name: Test
          command: |
            cd ./backend/
            mvn test
    
  frontend:
    docker:
      - image: cimg/node:18.0.0
      
    steps:
      - checkout:
        path: ~/frontend/
      - node/install-packages:
         pkg-manager: npm
      - run:
          name: Test
          command: ng test
      - run:
          name: Build
          command: ng build

# Invoke jobs via workflows
workflows:
  sample:
    jobs:
      - backend
      - frontend
