server:
  port: 0

spring:
  application:
    name: "auth"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create

app:
  init-test-data: true

jwt:
  secret: "secret"
  accessTokenMaxAgeInMinutes: 5
  refreshTokenMaxAgeInMinutes: 4320
